"use client";

import { motion } from "framer-motion";
import { Sparkles, Bot } from "lucide-react";
import { fadeUp } from "@/lib/motion";

interface AiExecutiveSummaryCardProps {
  summary: string | undefined;
}

/**
 * AiExecutiveSummaryCard
 *
 * Renders the AI-generated (or high-quality fallback) executive summary
 * at the top of every audit report.
 *
 * Visual design:
 *   - Elevated card with indigo/violet gradient border
 *   - "AI Summary" badge with Sparkles icon
 *   - Prose-style typography for readability
 *   - Subtle Gemini attribution
 *   - Skeleton state when summary is loading
 */
export function AiExecutiveSummaryCard({ summary }: AiExecutiveSummaryCardProps) {
  return (
    <motion.div
      variants={fadeUp}
      initial="hidden"
      animate="visible"
      className="relative overflow-hidden rounded-3xl p-px"
      style={{
        background:
          "linear-gradient(135deg, oklch(0.58 0.18 264 / 35%), oklch(0.55 0.18 290 / 25%), oklch(0.58 0.18 264 / 15%))",
      }}
    >
      {/* Inner card */}
      <div className="relative rounded-[calc(1.5rem-1px)] bg-gradient-to-br from-indigo-50/80 via-white to-violet-50/40 p-6 dark:from-indigo-950/60 dark:via-slate-950 dark:to-violet-950/30">

        {/* Ambient glow */}
        <div className="pointer-events-none absolute -right-16 -top-16 h-40 w-40 rounded-full bg-indigo-400/8 blur-3xl dark:bg-indigo-500/10" />
        <div className="pointer-events-none absolute -bottom-8 left-8 h-28 w-28 rounded-full bg-violet-400/6 blur-3xl dark:bg-violet-500/8" />

        {/* Header row */}
        <div className="relative flex items-center justify-between gap-3">
          <div className="flex items-center gap-2.5">
            {/* Icon badge */}
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 shadow-md shadow-indigo-500/25">
              <Sparkles className="h-4 w-4 text-white" />
            </div>
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.18em] text-indigo-600 dark:text-indigo-400">
                AI Executive Summary
              </p>
              <p className="text-[10px] text-slate-400">
                Personalized to your stack
              </p>
            </div>
          </div>

          {/* Gemini badge */}
          <div className="flex items-center gap-1.5 rounded-full border border-indigo-200/60 bg-white/60 px-3 py-1.5 dark:border-indigo-500/20 dark:bg-indigo-950/40">
            <Bot className="h-3 w-3 text-indigo-500 dark:text-indigo-400" />
            <span className="text-[10px] font-semibold text-indigo-600 dark:text-indigo-400">
              Gemini 2.5
            </span>
          </div>
        </div>

        {/* Divider */}
        <div className="relative mt-5 h-px bg-gradient-to-r from-indigo-200/60 via-violet-200/40 to-transparent dark:from-indigo-500/20 dark:via-violet-500/10" />

        {/* Summary text */}
        <div className="relative mt-5">
          {summary ? (
            <p className="text-[15px] font-[450] leading-[1.75] tracking-[-0.005em] text-slate-700 dark:text-slate-200">
              {summary}
            </p>
          ) : (
            // Skeleton state for audits without a summary (old records)
            <div className="space-y-3">
              <div className="h-4 w-full animate-pulse rounded-full bg-indigo-100/80 dark:bg-indigo-900/40" />
              <div className="h-4 w-[92%] animate-pulse rounded-full bg-indigo-100/60 dark:bg-indigo-900/30" />
              <div className="h-4 w-[85%] animate-pulse rounded-full bg-indigo-100/60 dark:bg-indigo-900/30" />
              <div className="h-4 w-[70%] animate-pulse rounded-full bg-indigo-100/40 dark:bg-indigo-900/20" />
            </div>
          )}
        </div>

        {/* Footer attribution */}
        <div className="relative mt-5 flex items-center gap-1.5 text-[11px] text-slate-400 dark:text-slate-500">
          <Sparkles className="h-3 w-3" />
          Generated by Gemini AI · Summarizes rule-based audit findings · Numbers are deterministic
        </div>
      </div>
    </motion.div>
  );
}
